repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [ '--quiet' ]

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-added-large-files

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0.0
    hooks:
      - id: upgrade-type-hints

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        types: [ python ]
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus", '--keep-runtime-typing']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-bugbear==20.11.1',
            'flake8-comprehensions==3.3.1',
            'flake8-quotes==3.2.0',
            'flake8-tidy-imports==4.2.1',
            'flake8-print==4.0.0',
            'flake8-mutable==1.2.0',
            'flake8-printf-formatting==1.1.2',
            'flake8-simplify==0.14.0',
            'flake8-pytest-style==1.3.0',
            'flake8-type-checking==1',
        ]
        args: [ '--enable-extensions=G' ]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck

#  - repo: local
#    hooks:
#      - id: mypy
#        name: mypy
#        entry: mypy
#        language: system
#        types: [ python ]
